# Generated by Django 3.1.13 on 2021-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210914_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='quizquestionchoices',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
