# Generated by Django 3.1.13 on 2021-09-15 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20210915_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
