from django.urls import path
from .views import (course_grade_api,course_quizzes_grade_api,semester_course_grade_api,midterm_grade_api,
                                year_midterm_api,course_data_api,announcement_detail_api,quiz_grade_search_api,
                                assignment_detail_api,quiz_data_api,quiz_grades_detail_api,course_quizzes_detail,
                                midterm_grade_search_api,student_semester_grade_api,students_semester_grade_detail_api,
                                grades_search_api,course_grades_detail_api,get_student_grades,check_quiz_time_api,
                                student_questions,course_questions,update_question,get_answers,create_answer,update_answer,
                                course_assignments_grade_api)


urlpatterns = [
    path('api/v1/grade/course/<course_code>/',course_grade_api,name='course-grade-api'),
    path('api/v1/grade/quizzes/<course_code>/',course_quizzes_grade_api,name='quizzes-grade-api'),
    path('api/v1/grade/assignments/<course_code>/',course_assignments_grade_api,name='course-assignment-grades-api'),
    path('api/v1/grade/year/<int:year>/semester/<semester>/',semester_course_grade_api,name='semester-grade-api'),
    path('api/v1/grade/midterm/course/<course_code>/<int:year>/',midterm_grade_api,name='midterm-grade-api'),
    path('api/v1/year/<int:year>/midterm/',year_midterm_api,name='year-midterms-api'),
    path('api/v1/course/<code>/',course_data_api,name='course-detail'),
    path('api/v1/announcement/<slug:slug>/',announcement_detail_api,name='announcement-detail'),
    path('api/v1/assignment/<slug:slug>/',assignment_detail_api,name='assignment-detail'),
    path('api/v1/quiz/<slug:slug>/',quiz_data_api,name='quiz-detail'),
    path('api/v1/quiz/<slug:slug>/grades/',quiz_grades_detail_api,name='quiz-grades-api'),
    path('api/v1/quiz/course/<course_code>/<int:year>/grades/',course_quizzes_detail,name='course-quizzes-grade-api'),
    path('api/v1/quiz/<slug:slug>/<int:mark>/<type>/search/',quiz_grade_search_api,name='quiz-grade-search-api'),
    path('api/v1/course/<course_code>/<semester>/<int:year>/midterm/<int:mark>/<type>/',midterm_grade_search_api,name='midterm-grade-search'),
    path('api/v1/grade/student/<college_id>/<semester>/<int:year>/',student_semester_grade_api,name='semester-course-grade'),
    path('api/v1/grade/semester/<semester>/<int:year>/',students_semester_grade_detail_api,name='grade-semester-api'),
    path('api/v1/grade/<course_code>/<int:grade>/<int:year>/<type>/search/',grades_search_api,name='grades-year-search-api'),
    path('api/v1/grade/<course>/<int:year>/',course_grades_detail_api,name='course-grade-api'),
    path('api/v1/student/grades/<student_id>/<int:year>/',get_student_grades,name='student-grades-api'),
    path('api/v1/quiz/<slug:slug>/time/',check_quiz_time_api,name='check-quiz-time-api'),
    path('api/v1/student/questions/all/',student_questions,name='student-questions-api'),
    path('api/v1/course/<course_code>/questions/',course_questions,name='course-questions-api'),
    path('api/v1/question/<slug:slug>/update/',update_question,name='update-question-api'),
    path('api/v1/student/course/question/answers/all/',get_answers,name='student-answers'),
    path('api/v1/question/<slug:question_slug>/answer/create/',create_answer,name='create-answer-api'),
    path('api/v1/answer/<slug:slug>/update/',update_answer,name='update-answer-api'),
]
