# Generated by Django 3.1.13 on 2021-09-14 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizzes', '0001_initial'),
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_auto_20210914_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='semestergrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='semestergrade',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.year'),
        ),
        migrations.AddField(
            model_name='semester',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grades.year'),
        ),
        migrations.AddField(
            model_name='quizgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_grade', to='courses.course'),
        ),
        migrations.AddField(
            model_name='quizgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='quizgrade',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_grade', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='quizgrade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_prof': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm', to='courses.course'),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm', to='grades.semester'),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_prof': False}, on_delete=django.db.models.deletion.CASCADE, related_name='midterm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm', to='grades.year'),
        ),
        migrations.AddField(
            model_name='grade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='grade',
            name='semester_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grades.semestergrade'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grade',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grade', to='grades.year'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='courses.assignment'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='grades.grade'),
        ),
        migrations.AddField(
            model_name='assignmentgrade',
            name='student',
            field=models.ForeignKey(limit_choices_to={'is_prof': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='semestergrade',
            constraint=models.UniqueConstraint(fields=('year', 'student', 'semester'), name='year_semsiters'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('semester', 'year'), name='unique_year'),
        ),
        migrations.AddConstraint(
            model_name='quizgrade',
            constraint=models.UniqueConstraint(fields=('student', 'quiz'), name='one_grade'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('year', 'course', 'student'), name='year_grade'),
        ),
        migrations.AddConstraint(
            model_name='assignmentgrade',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='one_assignment_one_mark'),
        ),
    ]
