# Generated by Django 3.1.13 on 2021-09-14 14:43

from django.db import migrations, models
import django.db.models.deletion
import users.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True, verbose_name='Announcement')),
                ('public', models.BooleanField(default=False)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs\\assignments')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('max_mark', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=150, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course_image', models.ImageField(default='images\\course_images\\default.png', upload_to=users.utils.PathAndRename('images\\course_images'))),
                ('course_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='docs\\files')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True, max_length=5, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
