# Generated by Django 3.1.13 on 2021-09-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210914_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='descreption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='coursefiles',
            name='slug',
            field=models.SlugField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
